In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow.keras 
import sklearn

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1= LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2= LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:,2])

X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [5]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('Geography',OneHotEncoder(), [1])], remainder='passthrough')
#onehotencoder = OneHotEncoder(categorical_features = [1])
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [6]:
X=X[:,1:]
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [10]:
clf=Sequential()

clf.add(Dense(6,kernel_initializer='uniform',activation='relu',input_dim=11))

clf.add(Dense(6,kernel_initializer='uniform',activation='relu'))

clf.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))
clf.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [12]:
clf.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 72        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [11]:
clf.fit(X_train,y_train,batch_size=10,epochs=100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 3s 379us/sample - loss: 0.4826 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 289us/sample - loss: 0.4300 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 275us/sample - loss: 0.4253 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 274us/sample - loss: 0.4201 - accuracy: 0.8161
Epoch 5/100
8000/8000 [==============================] - 2s 277us/sample - loss: 0.4171 - accuracy: 0.8254
Epoch 6/100
8000/8000 [==============================] - 2s 276us/sample - loss: 0.4145 - accuracy: 0.8284
Epoch 7/100
8000/8000 [==============================] - 2s 276us/sample - loss: 0.4136 - accuracy: 0.8317
Epoch 8/100
8000/8000 [==============================] - 2s 276us/sample - loss: 0.4122 - accuracy: 0.8321
Epoch 9/100
8000/8000 [==============================] - 2s 272us/sample - loss: 0.4112 - accuracy: 0.8338
Epoch 10/100
80

8000/8000 [==============================] - 2s 250us/sample - loss: 0.3998 - accuracy: 0.8361
Epoch 77/100
8000/8000 [==============================] - 2s 283us/sample - loss: 0.4004 - accuracy: 0.8353
Epoch 78/100
8000/8000 [==============================] - 2s 274us/sample - loss: 0.4007 - accuracy: 0.8361
Epoch 79/100
8000/8000 [==============================] - 2s 270us/sample - loss: 0.3998 - accuracy: 0.8346
Epoch 80/100
8000/8000 [==============================] - 2s 276us/sample - loss: 0.4006 - accuracy: 0.8354
Epoch 81/100
8000/8000 [==============================] - 2s 268us/sample - loss: 0.4004 - accuracy: 0.8355
Epoch 82/100
8000/8000 [==============================] - 2s 266us/sample - loss: 0.4003 - accuracy: 0.8357
Epoch 83/100
8000/8000 [==============================] - 2s 268us/sample - loss: 0.3999 - accuracy: 0.8360
Epoch 84/100
8000/8000 [==============================] - 2s 267us/sample - loss: 0.4006 - accuracy: 0.8340
Epoch 85/100
8000/8000 [=================

In [ ]:
prd=clf.predict(X_test)

In [ ]:
y_pred=(prd>0.50)

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [ ]:
print(cm)

In [ ]:
(1529+199)/2000


In [ ]:
new_prediction=clf.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

In [ ]:
new_prd=(new_prediction>0.50)

In [ ]:
print(new_prd)

In [ ]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
def build_classifier():
    
    clf=Sequential()
    clf.add(Dense(6,kernel_initializer='uniform',activation='relu',input_dim=11))
    clf.add(Dense(6,kernel_initializer='uniform',activation='relu'))
    clf.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))
    clf.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return clf

clf=KerasClassifier(build_fn=build_classifier,batch_size=10,epochs=100)
accuracies=cross_val_score(estimator=clf,X=X_train, y=y_train,cv=2 )


In [ ]:
accuracies

In [ ]:
mean=accuracies.mean()
variance=accuracies.std()
print(mean)
print(variance)